server:
  port: 8083
spring:
  profiles:
    active:
      - "default"
  application:
    name: coupons
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
data:
  info: default profile couponservice

