server:
  port: 8083
spring:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active:
      - "default"
  application:
    name: coupons
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true
  info:
    env:
      enabled: true
data:
  info: default profile couponservice

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

