spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/propfiles
          clone-on-start: true
          default-label: master
server:
  port: 8888
logging:
  level:
    org.springframework.cloud.config: DEBUG